Repository RAF-SI-2024/Banka-1-Backend, pull requests merged in 2025-03, with the labels that each got.

#72 Added OWNERS file
  OWNERS
Labels: size/S

#73 payment codes
  banking-service/src/main/java/com/banka1/banking/controllers/MetadataController.java
  banking-service/src/main/java/com/banka1/banking/models/helper/PaymentType.java
Labels: approved, size/M, lgtm

#75 Removed reverse proxy from compose.dev.yaml
  compose.dev.yaml
Labels: size/S, approved, lgtm

#77 Fix startup crash in banking service and update compose.full.yaml
  banking-service/src/main/java/com/banka1/banking/repository/AccountRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/InstallmentsRepository.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  compose.full.yaml
Labels: size/S, approved, lgtm

#76 Zadatak #64
  banking-service/src/main/java/com/banka1/banking/controllers/ExchangeController.java
  banking-service/src/main/java/com/banka1/banking/dto/ExchangePreviewDTO.java
  banking-service/src/main/java/com/banka1/banking/repository/ExchangePairRepository.java
  banking-service/src/main/java/com/banka1/banking/services/ExchangeService.java
  gradlew
Labels: approved, lgtm, size/L

#79 reseni konflikti
  banking-service/src/main/java/com/banka1/banking/controllers/LoanController.java
  banking-service/src/main/java/com/banka1/banking/models/Installment.java
  banking-service/src/main/java/com/banka1/banking/repository/AccountRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/CurrencyRepository.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/main/java/com/banka1/banking/services/TransactionService.java
Labels: approved, size/M, lgtm

#80 Konflikti
  banking-service/src/main/java/com/banka1/banking/controllers/LoanController.java
Labels: approved, size/M, lgtm

#81 Konflikti
  banking-service/src/main/java/com/banka1/banking/controllers/LoanController.java
Labels: approved, lgtm

#82 Fixed loan creation logic and tests
  banking-service/src/main/java/com/banka1/banking/bootstrap/BootstrapData.java
  banking-service/src/main/java/com/banka1/banking/config/ModelMapperConfig.java
  banking-service/src/main/java/com/banka1/banking/controllers/LoanController.java
  banking-service/src/test/java/com/banka1/banking/cucumber/ExternalTransferServiceCucumberTest.java
  banking-service/src/test/java/com/banka1/banking/service/LoanServiceTest.java
  banking-service/src/test/java/com/banka1/banking/service/accountService/CreateAccountTest.java
  banking-service/src/test/resources/features/external_transfer.feature
Labels: approved, size/M, lgtm

#83 Sprint3
  banking-service/src/main/java/com/banka1/banking/dto/request/CreateLoanDTO.java
  banking-service/src/main/java/com/banka1/banking/models/Installment.java
  banking-service/src/main/java/com/banka1/banking/repository/CurrencyRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/InstallmentsRepository.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/main/java/com/banka1/banking/services/TransactionService.java
  banking-service/src/test/java/com/banka1/banking/service/LoanPaymentSchedulerTest.java
  banking-service/src/test/java/com/banka1/banking/service/LoanServiceTest.java
Labels: approved, lgtm, size/L

#84 small fix
  banking-service/src/main/java/com/banka1/banking/bootstrap/BootstrapData.java
  banking-service/src/main/java/com/banka1/banking/controllers/LoanController.java
  banking-service/src/main/java/com/banka1/banking/models/Company.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/test/java/com/banka1/banking/service/LoanPaymentSchedulerTest.java
Labels: approved, lgtm, size/L

#91 trading service
  trading-service/.env
  trading-service/db/Bootstrap.go
  trading-service/db/Database.go
  trading-service/go.mod
  trading-service/go.sum
  trading-service/main.go
  trading-service/test.db
  trading-service/types/Models.go
  trading-service/types/Response.go
Labels: approved, lgtm

#93 Exchange, Listings and Stocks
  trading-service/.env
  trading-service/db/Database.go
  trading-service/exchanges/exchanges.csv
  trading-service/exchanges/load.go
  trading-service/listings/Options/Load.go
  trading-service/listings/forex/Load.go
  trading-service/listings/futures/Load.go
  trading-service/listings/stocks/Load.go
  trading-service/main.go
  trading-service/test.db
  trading-service/types/Listings.go
  trading-service/types/Models.go
Labels: approved, lgtm, size/XL

#96 Add prow job, healthchecks and change docker images
  .gitignore
  .prow/banking-service.yml
  .prow/build.yml
  .prow/notification-service.yml
  .prow/trading-service.yml
  .prow/user-service.yml
  Caddyfile
  banking-service/build.gradle
  banking-service/src/main/resources/application.properties
  compose.full.yaml
  notification-service/build.gradle
  settings.gradle.kts
  trading-service/Dockerfile
  trading-service/build.gradle
  user-service/build.gradle
Labels: approved, lgtm, size/XL

#95 Nije uradjena autorizacija(ko sme da setuje limit agentu) i nema testova.
  trading-service/.gitignore
  trading-service/controllers/ActuaryController.go
  trading-service/db/ResetAgentDailyLimit.go
  trading-service/dto/ActuaryDTO.go
  trading-service/dto/UpdateActuaryDTO.go
  trading-service/go.mod
  trading-service/go.sum
  trading-service/main.go
  trading-service/routes/Routes.go
  trading-service/services/EmployeeService.go
Labels: approved, lgtm, size/L

#99 Menjanje blokiranja i aktiviranja kartice
  banking-service/src/main/java/com/banka1/banking/controllers/CardController.java
  banking-service/src/main/java/com/banka1/banking/dto/UpdateCardDTO.java
  banking-service/src/main/java/com/banka1/banking/models/helper/CardStatus.java
  banking-service/src/main/java/com/banka1/banking/services/CardService.java
  banking-service/src/test/java/com/banka1/banking/service/CardServiceTest.java
Labels: approved, size/M, lgtm

#100 listing history
  trading-service/listings/finhub/Finhub.go
  trading-service/listings/stocks/Load.go
  trading-service/main.go
  trading-service/test.db
  trading-service/types/Listings.go
  user-service/src/main/java/com/banka1/user/model/helper/Department.java
Labels: approved, lgtm

#98 Implement Forex and include dummy data in the trading service docker image
  banking-service/src/main/java/com/banka1/banking/controllers/CardController.java
  compose.full.yaml
  trading-service/Dockerfile
  trading-service/db/Database.go
  trading-service/listings/forex/Load.go
  trading-service/listings/futures/Load.go
  trading-service/listings/futures/future_data.csv
  trading-service/main.go
  trading-service/test.db
  trading-service/types/Listings.go
  trading-service/types/Models.go
Labels: approved, lgtm, size/XL

#104 historycal data
  banking-service/src/main/java/com/banka1/banking/controllers/CardController.java
  banking-service/src/main/java/com/banka1/banking/dto/request/UpdateCardNameDTO.java
  banking-service/src/main/java/com/banka1/banking/models/Card.java
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
  banking-service/src/main/java/com/banka1/banking/services/CardService.java
  common/src/main/java/com/banka1/common/model/Department.java
  common/src/main/java/com/banka1/common/service/IAuthService.java
  common/src/main/java/com/banka1/common/service/implementation/GenericAuthService.java
  trading-service/.gitignore
  trading-service/controllers/ActuaryController.go
  trading-service/db/Database.go
  trading-service/db/ResetAgentDailyLimit.go
  trading-service/listings/Options/Load.go
  trading-service/listings/finhub/Finhub.go
  trading-service/main.go
  trading-service/test.db
  trading-service/types/Listings.go
  user-service/src/main/java/com/banka1/user/DTO/banking/CreateAccountWithoutOwnerIdDTO.java
  user-service/src/main/java/com/banka1/user/DTO/request/CreateCustomerRequest.java
  user-service/src/main/java/com/banka1/user/DTO/request/CreateEmployeeRequest.java
  user-service/src/main/java/com/banka1/user/DTO/request/UpdateCustomerRequest.java
  user-service/src/main/java/com/banka1/user/DTO/request/UpdateEmployeeRequest.java
  user-service/src/main/java/com/banka1/user/DTO/response/CustomerResponse.java
  user-service/src/main/java/com/banka1/user/DTO/response/EmployeeResponse.java
  user-service/src/main/java/com/banka1/user/bootstrap/BootstrapData.java
  user-service/src/main/java/com/banka1/user/config/SecurityConfig.java
  user-service/src/main/java/com/banka1/user/controllers/MetadataController.java
  user-service/src/main/java/com/banka1/user/model/Customer.java
  user-service/src/main/java/com/banka1/user/model/Employee.java
  user-service/src/main/java/com/banka1/user/service/AuthService.java
  user-service/src/main/java/com/banka1/user/service/CustomerService.java
  user-service/src/main/java/com/banka1/user/service/EmployeeService.java
  user-service/src/test/java/com/banka1/user/controllers/CustomerControllerTest.java
  user-service/src/test/java/com/banka1/user/controllers/EmployeeControllerTest.java
  user-service/src/test/java/com/banka1/user/controllers/SearchControllerTest.java
  user-service/src/test/java/com/banka1/user/services/CustomerServiceTest.java
  user-service/src/test/java/com/banka1/user/services/EmployeeServiceTest.java
Labels: approved, lgtm, size/L

#106 Changed put into post for card methods
  banking-service/src/main/java/com/banka1/banking/bootstrap/BootstrapData.java
  banking-service/src/main/java/com/banka1/banking/controllers/CardController.java
  trading-service/test.db
Labels: size/S, approved, lgtm

#107 Cucumber testovi za korisnički servis
  user-service/build.gradle
  user-service/src/test/java/com/banka1/user/cucumber/AuthCucumberTest.java
  user-service/src/test/java/com/banka1/user/cucumber/CucumberSpringConfiguration.java
  user-service/src/test/java/com/banka1/user/cucumber/CucumberTest.java
  user-service/src/test/java/com/banka1/user/cucumber/SearchCucumberTest.java
  user-service/src/test/resources/features/auth.feature
  user-service/src/test/resources/features/search.feature
Labels: approved, lgtm

#109 Radi boze
  banking-service/src/main/java/com/banka1/banking/dto/request/CreateLoanDTO.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/test/java/com/banka1/banking/service/LoanServiceTest.java
Labels: approved, lgtm, size/L

#110 auth middleware
  trading-service/go.mod
  trading-service/go.sum
  trading-service/main.go
  trading-service/middlewares/Auth.go
  trading-service/middlewares/Jwt.go
  trading-service/test.db
Labels: approved, size/M, lgtm

#117 Implemented viewing and approving orders and also some authn/authz stuff
  trading-service/listings/Options/Load.go
  trading-service/main.go
  trading-service/middlewares/Auth.go
  trading-service/orders/Orders.go
  trading-service/test.db
  trading-service/types/Listings.go
  trading-service/types/Models.go
  trading-service/types/Orders.go
Labels: approved, lgtm, size/L

#111 APP i Deny
  banking-service/src/main/java/com/banka1/banking/controllers/LoanController.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
Labels: approved, lgtm, size/L

#119 Make prow deploy job run only on main
  .prow/build.yml
Labels: approved, lgtm, size/XS

#130 jacoco coverage theshold and setup defined, also removed duplicate de…
  banking-service/build.gradle
  notification-service/build.gradle
  user-service/build.gradle
Labels: approved, lgtm, size/L

#122 Migrate from using BootstrapData for seeding the DB to SQL scripts
  banking-service/src/main/java/com/banka1/banking/bootstrap/BootstrapData.java
  banking-service/src/main/java/com/banka1/banking/models/Loan.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/main/resources/application-h2.properties
  banking-service/src/main/resources/application-postgres.properties
  banking-service/src/main/resources/application.properties
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/cucumber/CucumberSpringConfiguration.java
  banking-service/src/test/java/com/banka1/banking/cucumber/CucumberTest.java
  banking-service/src/test/java/com/banka1/banking/cucumber/ExternalTransferServiceCucumberTest.java
  banking-service/src/test/java/com/banka1/banking/cucumber/TransferStepDefinitions.java
  banking-service/src/test/java/com/banka1/banking/service/LoanPaymentSchedulerTest.java
  banking-service/src/test/resources/features/external_transfer.feature
  banking-service/src/test/resources/features/internal_transfer.feature
  trading-service/.env
  trading-service/main.go
  user-service/src/main/java/com/banka1/user/bootstrap/BootstrapData.java
  user-service/src/main/resources/application-h2.properties
  user-service/src/main/resources/application-postgres.properties
  user-service/src/main/resources/application.properties
  user-service/src/main/resources/data.sql
  user-service/src/main/resources/schema.sql
  user-service/src/test/java/com/banka1/user/AuthIntegrationTest.java
  user-service/src/test/java/com/banka1/user/SearchIntegrationTest.java
Labels: approved, lgtm, size/XXL

#113 Neke ispravke u Order modelu
  trading-service/orders/API.go
  trading-service/types/Models.go
  trading-service/types/Orders.go
Labels: approved, lgtm, size/L

#136 [WIP] Enable Jacoco coverage reporting
  .prow/banking-service.yml
  .prow/notification-service.yml
  .prow/user-service.yml
Labels: approved, lgtm, size/L

#141 Add service dependencies in compose files for CI
  .prow/banking-service.yml
  .prow/notification-service.yml
  .prow/trading-service.yml
  .prow/user-service.yml
  README.md
  compose.local.yaml
  compose.yaml
Labels: approved, lgtm, size/L

#138 Cucumber tests
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/controller/CardControllerTest.java
  banking-service/src/test/java/com/banka1/banking/controller/ExchangeControllerTest.java
  banking-service/src/test/java/com/banka1/banking/controller/RecieverControllerTest.java
  banking-service/src/test/java/com/banka1/banking/cucumber/CucumberSpringConfiguration.java
  banking-service/src/test/java/com/banka1/banking/cucumber/CucumberTest.java
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/AccountSteps.java
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/CardSteps.java
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/LoanAdminSteps.java
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/LoanRequestSteps.java
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/TransferSteps.java
  banking-service/src/test/java/com/banka1/banking/dto/DtoTest.java
  banking-service/src/test/resources/features/account.feature
  banking-service/src/test/resources/features/card.feature
  banking-service/src/test/resources/features/loan-admin.feature
  banking-service/src/test/resources/features/loan.feature
  banking-service/src/test/resources/features/transfer.feature
Labels: approved, lgtm, size/XXL

#143 Go Dummy Tests
  trading-service/go.mod
  trading-service/go.sum
  trading-service/services/dummy_test.go
  trading-service/test_test.go
Labels: approved, lgtm, size/XL

#145 Fix test failures
  .prow/banking-service.yml
  .prow/trading-service.yml
  .prow/user-service.yml
  compose.yaml
Labels: size/S, approved, lgtm

#146 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#140 pokusaj treci
  banking-service/src/main/java/com/banka1/banking/models/Company.java
  banking-service/src/main/java/com/banka1/banking/models/helper/AccountType.java
  banking-service/src/main/java/com/banka1/banking/repository/AccountRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/CompanyRepository.java
  banking-service/src/main/java/com/banka1/banking/services/BankAccountUtils.java
  banking-service/src/main/java/com/banka1/banking/services/BankAccountsInitializer.java
  banking-service/src/main/java/com/banka1/banking/services/UserServiceCustomer.java
  banking-service/src/main/resources/application.properties
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  user-service/build.gradle
  user-service/src/main/java/com/banka1/user/listener/CustomerListener.java
  user-service/src/main/java/com/banka1/user/repository/CustomerRepository.java
  user-service/src/main/java/com/banka1/user/service/AccountInitializer.java
  user-service/src/main/java/com/banka1/user/service/CustomerService.java
  user-service/src/main/resources/application.properties
  user-service/src/main/resources/data.sql
  user-service/src/test/java/com/banka1/user/SearchIntegrationTest.java
Labels: approved, lgtm, size/L

#147 Force sucess tests
  banking-service/build.gradle
  banking-service/src/test/java/com/banka1/banking/services/TransactionServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransferServiceTest.java
Labels: approved, lgtm, size/XL

#142 Swagger dokumentacija User Service-a, brisanje set-password ruta koje se ne koriste i bugfix
  user-service/src/main/java/com/banka1/user/DTO/banking/CreateAccountDTO.java
  user-service/src/main/java/com/banka1/user/config/SwaggerConfiguration.java
  user-service/src/main/java/com/banka1/user/controllers/AuthController.java
  user-service/src/main/java/com/banka1/user/controllers/CustomerController.java
  user-service/src/main/java/com/banka1/user/controllers/EmployeeController.java
  user-service/src/main/java/com/banka1/user/controllers/MetadataController.java
  user-service/src/main/java/com/banka1/user/controllers/ResetPasswordController.java
  user-service/src/main/java/com/banka1/user/controllers/SearchController.java
  user-service/src/main/java/com/banka1/user/controllers/SetPasswordController.java
  user-service/src/main/java/com/banka1/user/service/CustomerService.java
  user-service/src/main/java/com/banka1/user/service/EmployeeService.java
  user-service/src/main/java/com/banka1/user/service/ResetPasswordService.java
  user-service/src/main/java/com/banka1/user/utils/ResponseMessage.java
  user-service/src/test/java/com/banka1/user/services/CustomerServiceTest.java
  user-service/src/test/java/com/banka1/user/services/ResetPasswordServiceTest.java
Labels: approved, lgtm, size/XL

#148 UTF-8 encoding, swagger dokumentacija i sitni fixovi
  banking-service/src/main/java/com/banka1/banking/config/SwaggerConfiguration.java
  banking-service/src/main/java/com/banka1/banking/controllers/AccountController.java
  banking-service/src/main/java/com/banka1/banking/controllers/CardController.java
  banking-service/src/main/java/com/banka1/banking/dto/AuthorizedPersonDTO.java
  banking-service/src/main/java/com/banka1/banking/models/AuthorizedPerson.java
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
  banking-service/src/main/java/com/banka1/banking/services/ExchangeService.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/main/java/com/banka1/banking/utils/ResponseMessage.java
  banking-service/src/main/resources/application-postgres.properties
  banking-service/src/test/java/com/banka1/banking/dto/DtoTest.java
  notification-service/src/main/java/com/banka1/notification/service/EmailService.java
  user-service/src/main/java/com/banka1/user/listener/CustomerListener.java
  user-service/src/main/java/com/banka1/user/service/CustomerService.java
  user-service/src/main/java/com/banka1/user/service/EmployeeService.java
  user-service/src/main/java/com/banka1/user/service/ResetPasswordService.java
  user-service/src/main/resources/application-postgres.properties
Labels: approved, lgtm, size/XL

#150 prepravka cron funckije za exchangePair
  banking-service/src/main/java/com/banka1/banking/BankingServiceApplication.java
  banking-service/src/main/java/com/banka1/banking/services/CurrencyService.java
Labels: approved, lgtm, size/XS

#151 Izmene za bazu
  banking-service/src/main/resources/data.sql
  user-service/src/main/resources/data.sql
Labels: approved, lgtm, size/L, needs-ok-to-test

#155 Sprint 5 - Dopuna menjačnice
  banking-service/src/main/java/com/banka1/banking/models/Transaction.java
  banking-service/src/main/java/com/banka1/banking/services/ExchangeService.java
  banking-service/src/main/java/com/banka1/banking/services/TransactionService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/main/java/com/banka1/banking/utils/ExcludeFromGeneratedJacocoReport.java
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/services/ExternalTransferServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/ExternalTransferServiceUnitTest.java
  banking-service/src/test/java/com/banka1/banking/services/InternalTransferServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransactionServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransferServiceTest.java
Labels: approved, lgtm, size/XL

#159 firebase notifikacije
  banking-service/src/main/java/com/banka1/banking/dto/NotificationDTO.java
  banking-service/src/main/java/com/banka1/banking/services/ExchangeService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/test/java/com/banka1/banking/services/ExchangeServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransferServiceTest.java
  notification-service/.env
  notification-service/build.gradle
  notification-service/src/main/java/com/banka1/notification/DTO/request/AddDeviceDTO.java
  notification-service/src/main/java/com/banka1/notification/DTO/response/NotificationDTO.java
  notification-service/src/main/java/com/banka1/notification/Test.java
  notification-service/src/main/java/com/banka1/notification/aspect/AuthAspect.java
  notification-service/src/main/java/com/banka1/notification/aspect/Authorization.java
  notification-service/src/main/java/com/banka1/notification/config/FirebaseConfig.java
  notification-service/src/main/java/com/banka1/notification/controllers/NotificationController.java
  notification-service/src/main/java/com/banka1/notification/listener/NotificationListener.java
  notification-service/src/main/java/com/banka1/notification/model/CustomerDevice.java
  notification-service/src/main/java/com/banka1/notification/repository/CustomerDeviceRepository.java
  notification-service/src/main/java/com/banka1/notification/sender/EmailSender.java
  notification-service/src/main/java/com/banka1/notification/sender/FirebaseSender.java
  notification-service/src/main/java/com/banka1/notification/sender/NotificationSender.java
  notification-service/src/main/java/com/banka1/notification/service/DeviceService.java
  notification-service/src/main/java/com/banka1/notification/service/FirebaseService.java
  notification-service/src/main/java/com/banka1/notification/service/implementation/AuthService.java
  notification-service/src/main/java/com/banka1/notification/utils/ResponseMessage.java
  notification-service/src/main/java/com/banka1/notification/utils/ResponseTemplate.java
  notification-service/src/main/resources/application.properties
  notification-service/src/main/resources/firebase.json
  notification-service/src/test/java/com/banka1/notification/NotificationApplicationTests.java
  notification-service/src/test/java/com/banka1/notification/listener/NotificationListenerTest.java
  trading-service/test.db-journal
  user-service/src/main/resources/data.sql
Labels: approved, lgtm, size/XL

#157 Resen problemi koji su mi prijavljeni u exchange-u
  banking-service/src/main/java/com/banka1/banking/repository/TransactionRepository.java
  banking-service/src/main/java/com/banka1/banking/services/ExchangeService.java
  banking-service/src/main/java/com/banka1/banking/services/TransactionService.java
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/AccountSteps.java
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/CardSteps.java
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/LoanAdminSteps.java
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/LoanRequestSteps.java
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/TransferSteps.java
  banking-service/src/test/java/com/banka1/banking/services/ExchangeServiceTest.java
  compose.dev.yaml
  compose.yaml
Labels: approved, lgtm, size/L

#161 Ispravljanje kredita
  banking-service/src/main/java/com/banka1/banking/controllers/LoanController.java
  banking-service/src/main/java/com/banka1/banking/dto/EmployeeDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/InternalTransferDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/MoneyTransferDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/request/CreateLoanDTO.java
  banking-service/src/main/java/com/banka1/banking/models/Installment.java
  banking-service/src/main/java/com/banka1/banking/models/Loan.java
  banking-service/src/main/java/com/banka1/banking/models/RateChange.java
  banking-service/src/main/java/com/banka1/banking/models/Transaction.java
  banking-service/src/main/java/com/banka1/banking/repository/InstallmentsRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/RateChangeRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/TransactionRepository.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/main/java/com/banka1/banking/services/TransactionService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/main/java/com/banka1/banking/services/UserServiceEmployee.java
  banking-service/src/main/resources/application.properties
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/service/LoanPaymentSchedulerTest.java
  banking-service/src/test/java/com/banka1/banking/service/LoanServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransactionServiceTest.java
  user-service/src/main/java/com/banka1/user/listener/EmployeeListener.java
  user-service/src/main/java/com/banka1/user/repository/EmployeeRepository.java
  user-service/src/main/java/com/banka1/user/service/EmployeeService.java
  user-service/src/main/resources/application.properties
Labels: approved, lgtm, size/XXL

#158 Fix returning Forex, and remove volumes from compose files
  compose.dev.yaml
  compose.local.yaml
  trading-service/main.go
  user-service/build.gradle
Labels: size/S, approved, lgtm

#165 Popravio prikaz transakcija
  .gitignore
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
  banking-service/src/main/java/com/banka1/banking/services/TransactionService.java
  banking-service/src/test/java/com/banka1/banking/services/TransactionServiceTest.java
  notification-service/.env
  trading-service/.env
  user-service/.env
Labels: approved, size/M, lgtm

#163 Password fix
  user-service/src/main/resources/data.sql
Labels: approved, lgtm, size/XS

#162 Swagger dokumentacija
  banking-service/src/main/java/com/banka1/banking/controllers/CurrencyController.java
  banking-service/src/main/java/com/banka1/banking/controllers/ExchangeController.java
  banking-service/src/main/java/com/banka1/banking/controllers/LoanController.java
  banking-service/src/main/java/com/banka1/banking/controllers/TransactionController.java
  banking-service/src/main/java/com/banka1/banking/controllers/TransferController.java
  banking-service/src/main/java/com/banka1/banking/services/UserServiceEmployee.java
  banking-service/src/test/java/com/banka1/banking/services/ExternalTransferServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/InternalTransferServiceTest.java
Labels: approved, lgtm, size/XXL

#166 Milica fix
  banking-service/src/main/java/com/banka1/banking/aspect/CompanyAuthorization.java
  banking-service/src/main/java/com/banka1/banking/controllers/CompanyController.java
  banking-service/src/main/java/com/banka1/banking/dto/AuthorizedPersonDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/CreateCardDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/CreateCompanyDTO.java
  banking-service/src/main/java/com/banka1/banking/models/Company.java
  banking-service/src/main/java/com/banka1/banking/models/helper/BusinessActivityCode.java
  banking-service/src/main/java/com/banka1/banking/repository/CompanyRepository.java
  banking-service/src/main/java/com/banka1/banking/services/CardService.java
  banking-service/src/main/java/com/banka1/banking/services/CompanyService.java
  banking-service/src/main/java/com/banka1/banking/utils/ResponseMessage.java
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/CardSteps.java
  banking-service/src/test/java/com/banka1/banking/service/CompanyServiceTest.java
Labels: approved, lgtm, size/XL

#167 env :D
  .gitignore
  banking-service/.env
  notification-service/.env
  trading-service/.env
  user-service/.env
Labels: size/S, approved, lgtm

#168 Fix loans
  banking-service/src/main/java/com/banka1/banking/repository/RateChangeRepository.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  trading-service/test.db-journal
Labels: approved, size/M, lgtm

#181 Banking service cleanup
  banking-service/src/main/java/com/banka1/banking/config/ModelMapperConfig.java
  banking-service/src/main/java/com/banka1/banking/config/SecurityConfig.java
  banking-service/src/main/java/com/banka1/banking/controllers/AccountController.java
  banking-service/src/main/java/com/banka1/banking/controllers/ExchangeController.java
  banking-service/src/main/java/com/banka1/banking/controllers/LoanController.java
  banking-service/src/main/java/com/banka1/banking/controllers/OtpTokenController.java
  banking-service/src/main/java/com/banka1/banking/controllers/ReceiverController.java
  banking-service/src/main/java/com/banka1/banking/controllers/TransactionController.java
  banking-service/src/main/java/com/banka1/banking/controllers/TransferController.java
  banking-service/src/main/java/com/banka1/banking/dto/AuthorizedPersonDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/OtpTokenDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/ReceiverDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/UpdateCardLimitDTO.java
  banking-service/src/main/java/com/banka1/banking/listener/AccountListener.java
  banking-service/src/main/java/com/banka1/banking/listener/MessageHelper.java
  banking-service/src/main/java/com/banka1/banking/models/Account.java
  banking-service/src/main/java/com/banka1/banking/models/Card.java
  banking-service/src/main/java/com/banka1/banking/models/Currency.java
  banking-service/src/main/java/com/banka1/banking/models/OtpToken.java
  banking-service/src/main/java/com/banka1/banking/models/Receiver.java
  banking-service/src/main/java/com/banka1/banking/models/Transaction.java
  banking-service/src/main/java/com/banka1/banking/models/Transfer.java
  banking-service/src/main/java/com/banka1/banking/repository/AccountRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/AuthorizedPersonRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/InstallmentsRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/TransactionRepository.java
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
  banking-service/src/main/java/com/banka1/banking/services/AuthorizedPersonService.java
  banking-service/src/main/java/com/banka1/banking/services/BankAccountsInitializer.java
  banking-service/src/main/java/com/banka1/banking/services/CompanyService.java
  banking-service/src/main/java/com/banka1/banking/services/CurrencyService.java
  banking-service/src/main/java/com/banka1/banking/services/ExchangeService.java
  banking-service/src/main/java/com/banka1/banking/services/OtpTokenService.java
  banking-service/src/main/java/com/banka1/banking/services/ReceiverService.java
  banking-service/src/main/java/com/banka1/banking/services/UserServiceCustomer.java
Labels: approved, lgtm, size/L
