Repository RAF-SI-2024/Banka-1-Backend, pull requests merged in 2025-04, with the labels that each got.

#186 Dodata logika za upravljnje orderima, uradio sam edge-case-ove i napisao testove
  trading-service/db/Database.go
  trading-service/orders/API.go
  trading-service/orders/Matching.go
  trading-service/orders_test/order_matching_test.go
  trading-service/types/Transaction.go
Labels: approved, lgtm, size/L

#184 Fix business activity codes so that it matches the spec
  banking-service/src/main/java/com/banka1/banking/models/Company.java
  banking-service/src/main/java/com/banka1/banking/models/helper/BusinessActivityCode.java
  banking-service/src/main/java/com/banka1/banking/utils/ResponseMessage.java
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
Labels: approved, lgtm, size/L

#185 Dodata ruta i resen bug za expired date na Card
  banking-service/src/main/java/com/banka1/banking/services/CardService.java
  go.mod
  trading-service/controllers/PortfolioController.go
  trading-service/dto/PortfolioSecurityDTO.go
  trading-service/openapi.yml
  trading-service/routes/Routes.go
Labels: approved, lgtm, size/L

#189 API putanje za Tax Tracking page
  trading-service/main.go
  trading-service/tax/API.go
  trading-service/types/Models.go
  trading-service/types/Tax.go
Labels: approved, size/M, lgtm

#188 Stop and stop-limit orders
  trading-service/cron/CronJobs.go
  trading-service/orders/API.go
  trading-service/orders/ExecuteOrders.go
Labels: approved, lgtm, size/L

#191 Ispravka za Tax Tracking page
  trading-service/tax/API.go
Labels: approved, lgtm, size/XS

#193 Chatbot initial commit
  support-service/.gitignore
  support-service/application/chatbot.py
  support-service/application/main.py
  support-service/application/routes.py
Labels: approved, lgtm, size/L

#196 dodata ruta /tax/dashboard
  trading-service/tax/API.go
  trading-service/types/Tax.go
Labels: approved, lgtm, size/L

#198 Bootstrap for tax and securities
  trading-service/main.go
  trading-service/types/Models.go
Labels: approved, size/M, lgtm

#195 Sprint 6 - Market i Limit Order
  banking-service/src/main/java/com/banka1/banking/controllers/OrderController.java
  banking-service/src/main/java/com/banka1/banking/services/OrderService.java
  trading-service/.env
  trading-service/cron/CronJobs.go
  trading-service/go.mod
  trading-service/go.sum
  trading-service/main.go
  trading-service/middlewares/Jwt.go
  trading-service/orders/API.go
  trading-service/orders/ExecuteOrders.go
  trading-service/orders/Matching.go
Labels: approved, lgtm, size/L

#201 Changed securities
  trading-service/listings/Options/Load.go
  trading-service/listings/futures/Load.go
  trading-service/main.go
  trading-service/types/Models.go
Labels: approved, lgtm, size/L

#202 tax/dashboard
  trading-service/main.go
  trading-service/tax/API.go
Labels: approved, lgtm, size/L

#205 company fix
  banking-service/src/main/java/com/banka1/banking/controllers/CompanyController.java
  banking-service/src/main/java/com/banka1/banking/repository/AccountRepository.java
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
  banking-service/src/main/java/com/banka1/banking/services/CompanyService.java
Labels: approved, size/M, lgtm

#206 Swagger Dokumentacija za Trading Service i reorg koda
  trading-service/controllers/ActuaryController.go
  trading-service/controllers/ExchangeController.go
  trading-service/controllers/ForexController.go
  trading-service/controllers/FutureController.go
  trading-service/controllers/OptionsController.go
  trading-service/controllers/OrderController.go
  trading-service/controllers/PortfolioController.go
  trading-service/controllers/SecuritiesController.go
  trading-service/controllers/StockController.go
  trading-service/controllers/TaxController.go
  trading-service/controllers/orders/ExecuteOrders.go
  trading-service/controllers/orders/Matching.go
  trading-service/cron/CronJobs.go
  trading-service/docs/docs.go
  trading-service/docs/swagger.json
  trading-service/docs/swagger.yaml
  trading-service/dto/PortfolioSecurityDTO.go
  trading-service/go.mod
  trading-service/go.sum
  trading-service/listings/securities/Load.go
  trading-service/listings/tax/Load.go
  trading-service/main.go
  trading-service/middlewares/Jwt.go
  trading-service/routes/Routes.go
  trading-service/routes/Setup.go
Labels: approved, lgtm, size/XXL

#204 Dodao proveravanje greske kod kreiranja racuna tokom kreiranja musterije
  banking-service/src/main/java/com/banka1/banking/config/MessageHelperConfig.java
  banking-service/src/main/java/com/banka1/banking/listener/AccountListener.java
  banking-service/src/main/java/com/banka1/banking/listener/MessageHelper.java
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
  banking-service/src/main/java/com/banka1/banking/services/ExchangeService.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/main/java/com/banka1/banking/services/UserServiceCustomer.java
  banking-service/src/main/java/com/banka1/banking/services/UserServiceEmployee.java
  banking-service/src/test/java/com/banka1/banking/service/accountService/CreateAccountTest.java
  banking-service/src/test/java/com/banka1/banking/services/ExchangeServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransferServiceTest.java
  common/build.gradle
  common/src/main/java/com/banka1/common/listener/MessageHelper.java
  notification-service/src/main/java/com/banka1/notification/config/MessageHelperConfig.java
  notification-service/src/main/java/com/banka1/notification/listener/NotificationListener.java
  notification-service/src/test/java/com/banka1/notification/NotificationApplicationTests.java
  notification-service/src/test/java/com/banka1/notification/cucumber/steps/SendEmailSteps.java
  notification-service/src/test/java/com/banka1/notification/listener/MessageHelperTest.java
  notification-service/src/test/java/com/banka1/notification/listener/NotificationListenerTest.java
  user-service/src/main/java/com/banka1/user/config/MessageHelperConfig.java
  user-service/src/main/java/com/banka1/user/listener/CustomerListener.java
  user-service/src/main/java/com/banka1/user/listener/EmployeeListener.java
  user-service/src/main/java/com/banka1/user/listener/MessageHelper.java
  user-service/src/main/java/com/banka1/user/service/CustomerService.java
  user-service/src/main/java/com/banka1/user/service/EmployeeService.java
  user-service/src/main/java/com/banka1/user/service/ResetPasswordService.java
  user-service/src/test/java/com/banka1/user/services/CustomerServiceTest.java
  user-service/src/test/java/com/banka1/user/services/EmployeeServiceTest.java
  user-service/src/test/java/com/banka1/user/services/ResetPasswordServiceTest.java
Labels: approved, lgtm, size/L

#208 aktuar cron fix
  banking-service/src/main/resources/data.sql
  trading-service/cron/CronJobs.go
Labels: size/S, approved, lgtm

#207 /securities/available i /{userId}
  trading-service/controllers/SecuritiesController.go
  trading-service/controllers/SecurityController.go
  trading-service/controllers/orders/Load.go
  trading-service/dto/PortfolioSecurityDTO.go
  trading-service/listings/securities/Load.go
  trading-service/listings/tax/Load.go
  trading-service/main.go
  trading-service/portfolio/Load.go
  trading-service/types/Security.go
Labels: approved, lgtm, size/L

#209 Popravka swaggera
  trading-service/Dockerfile
  trading-service/docs/docs.go
  trading-service/docs/swagger.json
  trading-service/docs/swagger.yaml
  trading-service/main.go
Labels: size/S, approved, lgtm

#210 reseni konflikti i test za trading-service
  .gitignore
  trading-service/controllers/ActuaryController.go
  trading-service/dto/ActuaryDTO.go
  trading-service/routes/Routes.go
  trading-service/services/EmployeeService.go
  user-service/src/main/java/com/banka1/user/controllers/EmployeeController.java
  user-service/src/main/java/com/banka1/user/repository/EmployeeRepository.java
  user-service/src/main/java/com/banka1/user/service/EmployeeService.java
Labels: approved, lgtm, size/L

#211 Dodata ruta PUT /securities/public-count
  trading-service/controllers/PortfolioController.go
  trading-service/controllers/SecuritiesController.go
  trading-service/dto/PortfolioSecurityDTO.go
  trading-service/portfolio/Load.go
  trading-service/routes/Setup.go
  trading-service/types/Models.go
Labels: approved, lgtm, size/L

#217 error 500 poruke, fix kreiranje
  Caddyfile
  banking-service/src/main/java/com/banka1/banking/config/GlobalExceptionHandler.java
  banking-service/src/main/java/com/banka1/banking/listener/AccountListener.java
  compose.yaml
  user-service/src/main/java/com/banka1/user/config/GlobalExceptionHandler.java
  user-service/src/main/java/com/banka1/user/service/CustomerService.java
Labels: approved, size/M, lgtm

#218 Fix build failure
  trading-service/controllers/PortfolioController.go
  trading-service/docs/docs.go
  trading-service/docs/swagger.json
  trading-service/docs/swagger.yaml
Labels: approved, lgtm, size/L

#220 :D
  banking-service/src/main/java/com/banka1/banking/controllers/CompanyController.java
  banking-service/src/main/java/com/banka1/banking/models/helper/BusinessActivityCode.java
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
Labels: size/S, approved, lgtm

#216 Unapredjenje portala za upravljanje aktuarima
  trading-service/controllers/ActuaryController.go
  trading-service/controllers/OrderController.go
  trading-service/controllers/orders/Matching.go
  trading-service/cron/CronJobs.go
  trading-service/dto/ActuaryDTO.go
  trading-service/main.go
  trading-service/middlewares/Auth.go
  trading-service/routes/Routes.go
  trading-service/services/EmployeeService.go
  trading-service/types/Models.go
  user-service/src/main/java/com/banka1/user/controllers/EmployeeController.java
  user-service/src/main/java/com/banka1/user/repository/EmployeeRepository.java
  user-service/src/main/java/com/banka1/user/service/EmployeeService.java
  user-service/src/main/resources/data.sql
Labels: approved, lgtm, size/L

#222 Prebacen sqlite u postgres, popravljeni bagovi sa transakcijama
  trading-service/.env
  trading-service/controllers/TaxController.go
  trading-service/controllers/orders/Matching.go
  trading-service/db/Database.go
  trading-service/docs/docs.go
  trading-service/docs/swagger.json
  trading-service/docs/swagger.yaml
  trading-service/go.mod
  trading-service/go.sum
Labels: approved, lgtm, size/XL

#223 firebase kriminal
  compose.yaml
  notification-service/src/main/java/com/banka1/notification/config/FirebaseConfig.java
  notification-service/src/main/resources/firebase.json
  notification-service/src/main/resources/firebase.txt
Labels: approved, size/M, lgtm

#228 Fix trading-service startup crashes
  compose.local.yaml
  compose.yaml
  trading-service/cron/CronJobs.go
Labels: approved, size/M, lgtm

#226 front sync promene
  banking-service/src/main/java/com/banka1/banking/controllers/AccountController.java
  banking-service/src/main/java/com/banka1/banking/dto/TransactionResponseDTO.java
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
Labels: approved, size/M, lgtm

#231 Resen Margin i bug fix
  banking-service/src/main/java/com/banka1/banking/controllers/LoanController.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  trading-service/controllers/OrderController.go
Labels: approved, lgtm, size/L

#232 opcije
  go.mod
  trading-service/controllers/OptionsController.go
  trading-service/listings/option/Load.go
  trading-service/main.go
Labels: approved, lgtm, size/L

#230 Otc trading
  banking-service/src/main/java/com/banka1/banking/dto/OTCPremiumFeeDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/OTCTransactionACKDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/OTCTransactionInitiationDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/request/UserAccountsResponse.java
  banking-service/src/main/java/com/banka1/banking/dto/request/UserRequest.java
  banking-service/src/main/java/com/banka1/banking/listener/AccountListener.java
  banking-service/src/main/java/com/banka1/banking/listener/OTCListener.java
  banking-service/src/main/java/com/banka1/banking/saga/OTCTransaction.java
  banking-service/src/main/java/com/banka1/banking/saga/OTCTransactionStage.java
  banking-service/src/main/java/com/banka1/banking/services/OTCService.java
  banking-service/src/main/resources/application.properties
  banking-service/src/test/java/com/banka1/banking/saga/OTCTest.java
  common/src/main/java/com/banka1/common/listener/MessageHelper.java
  common/src/main/java/com/banka1/common/model/Permission.java
  compose.local.yaml
  compose.yaml
  trading-service/.env
  trading-service/broker/broker.go
  trading-service/broker/listeners.go
  trading-service/broker/types.go
  trading-service/broker/wrappers.go
  trading-service/controllers/OTCTradeController.go
  trading-service/controllers/OrderController.go
  trading-service/controllers/orders/Load.go
  trading-service/cron/CronJobs.go
  trading-service/db/Database.go
  trading-service/dto/Account.go
  trading-service/go.mod
  trading-service/go.sum
  trading-service/main.go
  trading-service/middlewares/Auth.go
  trading-service/routes/Setup.go
  trading-service/saga/Saga.go
  trading-service/types/Models.go
  trading-service/types/OtcToBankingService.go
  user-service/src/main/resources/data.sql
  user-service/src/main/resources/schema.sql
Labels: approved, lgtm, size/XXL

#234 Popravio imena env promenjivih za trading servis
  compose.local.yaml
  compose.yaml
  trading-service/.env
  trading-service/main.go
Labels: size/S, approved, lgtm

#235 Sredjena ruta za zvanje loan-a iz order-a
  trading-service/controllers/OrderController.go
Labels: approved, lgtm, size/XS

#236 history za future i forex
  trading-service/controllers/ForexController.go
  trading-service/controllers/FutureController.go
  trading-service/cron/CronJobs.go
  trading-service/db/Database.go
  trading-service/types/Listings.go
Labels: approved, lgtm, size/L

#237 Otc trading fix
  trading-service/broker/listeners.go
  trading-service/controllers/OTCTradeController.go
Labels: approved, size/M, lgtm

#238 lista transfera
  banking-service/src/main/java/com/banka1/banking/controllers/TransferController.java
  banking-service/src/main/java/com/banka1/banking/repository/TransferRepository.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
Labels: approved, size/M, lgtm

#239 Reject offer fix
  trading-service/controllers/OTCTradeController.go
Labels: approved, lgtm, size/XS

#240 Context prompt and routing fix
  support-service/application/chatbot.py
  support-service/application/main.py
  support-service/application/routes.py
Labels: approved, size/M, lgtm

#241 loading fix
  trading-service/controllers/orders/Load.go
  trading-service/listings/forex/Load.go
  trading-service/listings/futures/Load.go
  trading-service/listings/stocks/Load.go
  trading-service/listings/tax/Load.go
  trading-service/main.go
Labels: approved, lgtm, size/L

#244 Popravio Swagger
  banking-service/src/main/java/com/banka1/banking/config/GlobalExceptionHandler.java
  notification-service/src/main/java/com/banka1/notification/config/GlobalExceptionHandler.java
  user-service/src/main/java/com/banka1/user/config/GlobalExceptionHandler.java
Labels: approved, lgtm, size/XS

#242 Fix
  .prow/build.yml
  Caddyfile
  compose.yaml
  settings.gradle.kts
  support-service/Dockerfile
  support-service/application/chatbot.py
  support-service/application/ctx.txt
  support-service/application/main.py
  support-service/build.gradle
  support-service/requirements.txt
Labels: approved, lgtm, size/L

#246 Client role
  banking-service/src/main/java/com/banka1/banking/controllers/AccountController.java
  banking-service/src/main/java/com/banka1/banking/models/AuthorizedPerson.java
  banking-service/src/main/java/com/banka1/banking/repository/CardRepository.java
  banking-service/src/main/java/com/banka1/banking/services/CardService.java
  banking-service/src/test/java/com/banka1/banking/service/CardServiceTest.java
Labels: size/S, approved, lgtm

#248 /actuaries/profits dodata ova ruta u InitActuaryRoutes
  trading-service/controllers/ActuaryController.go
Labels: approved, lgtm, size/XS

#251 fixes
  banking-service/src/main/java/com/banka1/banking/config/GlobalExceptionHandler.java
  banking-service/src/main/java/com/banka1/banking/dto/AuthorizedPersonDTO.java
  banking-service/src/main/java/com/banka1/banking/models/AuthorizedPerson.java
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
  banking-service/src/test/java/com/banka1/banking/dto/DtoTest.java
  user-service/src/main/java/com/banka1/user/DTO/banking/CreateAccountDTO.java
Labels: size/S, approved, lgtm

#250 azuriranje quantity i availableQuantity pri createOrder
  trading-service/controllers/OrderController.go
  trading-service/controllers/PortfolioController.go
  trading-service/controllers/SecuritiesController.go
  trading-service/controllers/SecurityController.go
  trading-service/controllers/orders/Matching.go
  trading-service/db/Database.go
  trading-service/types/Transaction.go
Labels: approved, lgtm, size/L

#258 Go tests :)
  trading-service/Makefile
  trading-service/controllers/actuary_test.go
  trading-service/controllers/exchange_test.go
  trading-service/controllers/portfolio_test.go
  trading-service/controllers/securities_test.go
  trading-service/controllers/stokc_test.go
  trading-service/controllers/tax_test.go
  trading-service/cron/cron_test.go
  trading-service/go.mod
  trading-service/go.sum
  trading-service/orders_test/order_matching_test.go
  trading-service/portfolio/Load_test.go
  trading-service/routes/routes_test.go
  trading-service/saga/Saga_test.go
  trading-service/services/dummy_test.go
  trading-service/services/services_test.go
  trading-service/test_test.go
  trading-service/types/types_test.go
Labels: approved, lgtm, size/XXL

#259 Dodata logika za pravljenje trasnakcija kada se kreira order
  banking-service/src/main/java/com/banka1/banking/services/OrderService.java
Labels: approved, size/M, lgtm

#260 MatchOrder sredjen
  trading-service/controllers/OrderController.go
  trading-service/controllers/orders/Matching.go
Labels: approved, lgtm, size/L

#263 Dopunjen coverage na testovima
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/test/java/com/banka1/banking/services/AccountServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/LoanServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/OrderServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/OtcServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransferServiceTest.java
  notification-service/src/test/java/com/banka1/notification/controller/NotificationControllerTest.java
  notification-service/src/test/java/com/banka1/notification/service/AuthAspectTest.java
  notification-service/src/test/java/com/banka1/notification/service/DeviceServiceTest.java
  notification-service/src/test/java/com/banka1/notification/service/FirebaseServiceTest.java
Labels: approved, lgtm, size/XXL

#265 CreateOrder (Buy i Sell) i azuriranje Public u Portfolio koje se pojavljuje u OTC Trading
  trading-service/controllers/OrderController.go
  trading-service/controllers/PortfolioController.go
  trading-service/controllers/SecuritiesController.go
  trading-service/controllers/orders/Matching.go
  trading-service/controllers/portfolio_test.go
  trading-service/dto/PortfolioSecurityDTO.go
  trading-service/main.go
Labels: approved, lgtm, size/XL

#264 Zavrsen rad sa orderima.
  banking-service/src/main/java/com/banka1/banking/controllers/OrderController.java
  banking-service/src/main/java/com/banka1/banking/services/OrderService.java
  banking-service/src/test/java/com/banka1/banking/services/OrderServiceTest.java
  trading-service/controllers/OrderController.go
  trading-service/controllers/PortfolioController.go
  trading-service/controllers/SecuritiesController.go
  trading-service/controllers/orders/Matching.go
  trading-service/controllers/orders_test.go
  trading-service/controllers/portfolio_test.go
  trading-service/dto/PortfolioSecurityDTO.go
  trading-service/middlewares/Jwt.go
Labels: approved, lgtm, size/XL

#245 Reciever se sada vezuje za customer-a umesto za racun. U bazi dodati …
  banking-service/src/main/java/com/banka1/banking/aspect/AuthAspect.java
  banking-service/src/main/java/com/banka1/banking/controllers/ReceiverController.java
  banking-service/src/main/java/com/banka1/banking/dto/InternalTransferDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/MoneyTransferDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/ReceiverDTO.java
  banking-service/src/main/java/com/banka1/banking/models/Receiver.java
  banking-service/src/main/java/com/banka1/banking/models/Transfer.java
  banking-service/src/main/java/com/banka1/banking/repository/ReceiverRepository.java
  banking-service/src/main/java/com/banka1/banking/services/LoanService.java
  banking-service/src/main/java/com/banka1/banking/services/ReceiverService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/service/AuthServiceTests.java
  banking-service/src/test/java/com/banka1/banking/services/ReceiverServiceTest.java
  user-service/src/main/java/com/banka1/user/controllers/EmployeeController.java
  user-service/src/main/java/com/banka1/user/repository/EmployeeRepository.java
  user-service/src/main/java/com/banka1/user/service/EmployeeService.java
Labels: approved, lgtm, size/L

#268 Remove table owners
  banking-service/src/main/resources/schema.sql
  notification-service/src/main/resources/application.properties
  user-service/src/main/resources/schema.sql
Labels: approved, size/M, lgtm

#267 Sprint 8 - OTC Bugfix
  banking-service/src/main/java/com/banka1/banking/listener/OTCListener.java
  banking-service/src/main/java/com/banka1/banking/models/OTCTransaction.java
  banking-service/src/main/java/com/banka1/banking/repository/OTCTransactionRepository.java
  banking-service/src/main/java/com/banka1/banking/saga/OTCTransaction.java
  banking-service/src/main/java/com/banka1/banking/saga/OTCTransactionStage.java
  banking-service/src/main/java/com/banka1/banking/services/OTCService.java
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/services/OtcServiceTest.java
Labels: approved, lgtm, size/L

#269 event delivery system
  banking-service/src/main/java/com/banka1/banking/bootstrap/BootstrapExchangeRateLoader.java
  banking-service/src/main/java/com/banka1/banking/dto/CreateEventDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/CreateEventDeliveryDTO.java
  banking-service/src/main/java/com/banka1/banking/models/Event.java
  banking-service/src/main/java/com/banka1/banking/models/EventDelivery.java
  banking-service/src/main/java/com/banka1/banking/models/helper/DeliveryStatus.java
  banking-service/src/main/java/com/banka1/banking/models/helper/IdempotenceKey.java
  banking-service/src/main/java/com/banka1/banking/repository/EventDeliveryRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/EventRepository.java
  banking-service/src/main/java/com/banka1/banking/services/EventExecutorService.java
  banking-service/src/main/java/com/banka1/banking/services/EventService.java
  banking-service/src/main/resources/schema.sql
Labels: approved, lgtm, size/L

#270 Dodata logika za profit
  trading-service/controllers/OrderController.go
  trading-service/controllers/orders_test.go
  trading-service/dto/ProfitDTO.go
  trading-service/services/ProfitService.go
Labels: approved, lgtm, size/L

#271 U metodi updateReceiver je parametar promenjen sa id na receiverId ka…
  banking-service/src/main/java/com/banka1/banking/controllers/ReceiverController.java
Labels: approved, lgtm, size/XS

#272 pracanje Volume-a Securitija
  trading-service/controllers/OrderController.go
  trading-service/controllers/orders/Matching.go
  trading-service/listings/securities/Load.go
  trading-service/main.go
Labels: approved, lgtm, size/L

#274 event delivery system
  banking-service/src/main/java/com/banka1/banking/bootstrap/BootstrapExchangeRateLoader.java
  banking-service/src/main/java/com/banka1/banking/config/CachedBodyFilter.java
  banking-service/src/main/java/com/banka1/banking/config/InterbankDeliveryInterceptor.java
  banking-service/src/main/java/com/banka1/banking/config/InterbankInterceptor.java
  banking-service/src/main/java/com/banka1/banking/config/WebConfig.java
  banking-service/src/main/java/com/banka1/banking/controllers/InterbankController.java
  banking-service/src/main/java/com/banka1/banking/dto/CreateEventDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/InterbankMessageDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/InterbankMessageType.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/committx/CommitTransactionDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/AssetDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/ForeignBankIdDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/InterbankTransactionDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/PostingDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/TxAccountDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/VerificationTokenDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/rollbacktx/RollbackTransactionDTO.java
  banking-service/src/main/java/com/banka1/banking/models/Event.java
  banking-service/src/main/java/com/banka1/banking/models/interbank/EventDirection.java
  banking-service/src/main/java/com/banka1/banking/repository/EventRepository.java
  banking-service/src/main/java/com/banka1/banking/services/EventExecutorService.java
  banking-service/src/main/java/com/banka1/banking/services/EventService.java
  banking-service/src/main/java/com/banka1/banking/services/InterbankService.java
  banking-service/src/main/resources/schema.sql
Labels: approved, lgtm, size/XL

#273 Fix swag error that killed the build
  trading-service/controllers/OrderController.go
Labels: approved, lgtm, size/XS

#275 front teamup bugfix
  banking-service/src/main/java/com/banka1/banking/dto/AuthorizedPersonDTO.java
  banking-service/src/main/java/com/banka1/banking/mapper/CardMapper.java
  banking-service/src/main/java/com/banka1/banking/services/CardService.java
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/service/CardServiceTest.java
  banking-service/src/test/java/com/banka1/banking/service/accountService/CreateAccountTest.java
  trading-service/controllers/OrderController.go
  trading-service/controllers/TaxController.go
Labels: approved, lgtm, size/L

#277 Go tests fix again
  trading-service/controllers/actuary_test.go
  trading-service/controllers/orders_test.go
  trading-service/controllers/stokc_test.go
  trading-service/cron/cron_test.go
  trading-service/go.mod
  trading-service/go.sum
  trading-service/listings/stocks/stocks_test.go
  trading-service/listings/tax/tax_test.go
  trading-service/middlewares/middle_test.go
  trading-service/services/services_test.go
Labels: approved, lgtm, size/XL

#279 Sredjeno za securities/id
  trading-service/controllers/SecuritiesController.go
Labels: approved, lgtm, size/XS

#278 idk
  trading-service/controllers/TaxController.go
Labels: approved, lgtm, size/L

#280 Resen bug za azuriranje volume u security
  trading-service/controllers/OrderController.go
  trading-service/controllers/SecuritiesController.go
  trading-service/controllers/orders/Load.go
  trading-service/controllers/orders/Matching.go
  trading-service/main.go
  trading-service/types/Orders.go
Labels: approved, lgtm, size/L

#284 Enable running of trading-service tests and swagger docs gen in CI
  .prow/trading-service.yml
  trading-service/controllers/OrderController.go
  trading-service/controllers/PortfolioController.go
  trading-service/controllers/portfolio_test.go
  trading-service/controllers/tax_test.go
  trading-service/routes/routes_test.go
Labels: approved, lgtm, size/L

#281 Tax ruta, closed accounts, cron job
  banking-service/src/main/java/com/banka1/banking/repository/AccountRepository.java
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
  trading-service/controllers/TaxController.go
  trading-service/controllers/tax_test.go
  trading-service/cron/CronJobs.go
  trading-service/docs/docs.go
  trading-service/docs/swagger.json
  trading-service/docs/swagger.yaml
  trading-service/main.go
  trading-service/routes/Routes.go
  trading-service/routes/routes_test.go
Labels: approved, lgtm, size/XL

#287 Resena greska koji je postojao sa kreiranjem transkacija kada se order pr…
  banking-service/src/main/java/com/banka1/banking/controllers/OrderController.java
  banking-service/src/main/java/com/banka1/banking/dto/OrderTransactionInitiationDTO.java
  banking-service/src/main/java/com/banka1/banking/listener/OrderListener.java
  banking-service/src/main/java/com/banka1/banking/services/OrderService.java
  banking-service/src/main/resources/application.properties
  trading-service/broker/broker.go
  trading-service/controllers/OrderController.go
  trading-service/controllers/orders/Load.go
  trading-service/controllers/orders/Matching.go
  trading-service/controllers/orders_test.go
  trading-service/dto/OrderTransactionInitiationDTO.go
  trading-service/middlewares/Jwt.go
Labels: approved, lgtm, size/L

#289 Make swag run outside of docker container
  .prow/trading-service.yml
Labels: approved, lgtm, size/XS

#292 OTC fix
  banking-service/src/main/java/com/banka1/banking/config/InterbankDeliveryInterceptor.java
  banking-service/src/main/java/com/banka1/banking/services/OTCService.java
  banking-service/src/test/java/com/banka1/banking/services/OtcServiceTest.java
  trading-service/broker/listeners.go
  trading-service/controllers/OTCTradeController.go
  trading-service/controllers/PortfolioController.go
  trading-service/docs/docs.go
  trading-service/docs/swagger.json
  trading-service/docs/swagger.yaml
  trading-service/go.mod
  trading-service/go.sum
Labels: approved, lgtm, size/L

#291 New payment logic
  banking-service/src/main/java/com/banka1/banking/services/ExchangeService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
Labels: approved, lgtm, size/L

#294 Ispravke u match-ovanju order-a
  banking-service/src/main/java/com/banka1/banking/listener/OrderListener.java
  banking-service/src/main/java/com/banka1/banking/services/OrderService.java
  trading-service/broker/broker.go
  trading-service/broker/wrappers.go
  trading-service/controllers/orders/Matching.go
  trading-service/main.go
Labels: approved, lgtm, size/L

#295 receiver fix
  banking-service/src/main/java/com/banka1/banking/controllers/ReceiverController.java
Labels: approved, lgtm, size/XS

#298 Tax Info fix
  trading-service/controllers/TaxController.go
Labels: approved, lgtm, size/XS

#300 Fixed pp
  trading-service/controllers/orders/Matching.go
Labels: approved, lgtm, size/XS

#296 cron job?
  trading-service/controllers/TaxController.go
  trading-service/go.mod
  trading-service/go.sum
Labels: approved, size/M, lgtm

#282 Error handling trading service
  trading-service/controllers/ActuaryController.go
  trading-service/controllers/ExchangeController.go
  trading-service/controllers/actuary_test.go
Labels: approved, lgtm, size/XL

#302 Bug pri pravljenju margin koji je neuspesan, i logika za availableQuantity doradjena
  trading-service/controllers/OrderController.go
  trading-service/controllers/PortfolioController.go
  trading-service/controllers/orders/Matching.go
Labels: approved, lgtm, size/L

#299 Računanje cene za OTC transakcije
  trading-service/broker/listeners.go
  trading-service/controllers/OTCTradeController.go
  trading-service/types/Transaction.go
Labels: approved, size/M, lgtm

#303 UpdateUsedLimit je sada samo obicna metoda i prosledjuju joj se id i amount, umesto post zahtevaNew route
  trading-service/controllers/ActuaryController.go
Labels: approved, size/M, lgtm

#304 taxrun sa testom
  trading-service/controllers/TaxController.go
  trading-service/controllers/tax_test.go
  trading-service/types/Transaction.go
Labels: approved, lgtm, size/L

#305 Dodao rutu za profit banke /profit/bank
  trading-service/controllers/OrderController.go
  trading-service/controllers/orders/Matching.go
  trading-service/dto/ProfitDTO.go
  trading-service/services/ProfitService.go
  trading-service/types/Transaction.go
Labels: approved, lgtm, size/L

#306 U bazu je dodat u tax tabelu jos jedan red zbog testiranja rute /actuaries/profits
  trading-service/listings/tax/Load.go
Labels: approved, size/M, lgtm

#307 cron job za resetovanje usedLimita za agente svakog dana u 23:59 je i…
  trading-service/cron/CronJobs.go
Labels: approved, lgtm, size/XS

#308 Dodao USD naloge za aktuare
  banking-service/src/main/resources/data.sql
Labels: size/S, approved, lgtm

#290 foreign bank transfer
  banking-service/src/main/java/com/banka1/banking/bootstrap/BootstrapExchangeRateLoader.java
  banking-service/src/main/java/com/banka1/banking/config/InterbankInterceptor.java
  banking-service/src/main/java/com/banka1/banking/controllers/InterbankController.java
  banking-service/src/main/java/com/banka1/banking/controllers/ReceiverController.java
  banking-service/src/main/java/com/banka1/banking/dto/CreateEventDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/ReceiverDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/VoteDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/VoteReasonDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/AssetDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/ForeignBankIdDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/InterbankTransactionDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/PostingDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/TxAccountDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/assets/CurrencyAsset.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/assets/MonetaryAssetDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/assets/OptionAssetDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/assets/OptionDescription.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/assets/StockAssetDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/assets/StockDescription.java
  banking-service/src/main/java/com/banka1/banking/models/Account.java
  banking-service/src/main/java/com/banka1/banking/models/Transaction.java
  banking-service/src/main/java/com/banka1/banking/models/Transfer.java
  banking-service/src/main/java/com/banka1/banking/models/helper/CurrencyType.java
  banking-service/src/main/java/com/banka1/banking/models/helper/IdempotenceKey.java
  banking-service/src/main/java/com/banka1/banking/models/helper/TransferStatus.java
  banking-service/src/main/java/com/banka1/banking/models/helper/TransferType.java
  banking-service/src/main/java/com/banka1/banking/repository/EventRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/ReceiverRepository.java
  banking-service/src/main/java/com/banka1/banking/services/AccountService.java
  banking-service/src/main/java/com/banka1/banking/services/EventExecutorService.java
  banking-service/src/main/java/com/banka1/banking/services/EventService.java
  banking-service/src/main/java/com/banka1/banking/services/InterbankOperationService.java
  banking-service/src/main/java/com/banka1/banking/services/InterbankService.java
  banking-service/src/main/java/com/banka1/banking/services/ReceiverService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/main/resources/schema.sql
  trading-service/main.go
Labels: approved, lgtm, size/XXL

#310 fix za transakcije i datume :DDDD
  banking-service/src/main/java/com/banka1/banking/models/Transaction.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  trading-service/controllers/TaxController.go
  trading-service/controllers/tax_test.go
  trading-service/types/Models.go
Labels: approved, lgtm, size/L

#311 Ispravke nekih trading service bootstrap podataka i neke druge ispravke
  banking-service/src/main/java/com/banka1/banking/services/OrderService.java
  banking-service/src/main/resources/data.sql
  banking-service/src/test/java/com/banka1/banking/cucumber/steps/TransferSteps.java
  trading-service/controllers/orders/Load.go
  trading-service/services/ProfitService.go
Labels: approved, size/M, lgtm

#312 Nadam se da je ovo kraj ordera.
  banking-service/src/main/java/com/banka1/banking/controllers/OrderController.java
  banking-service/src/main/java/com/banka1/banking/services/OrderService.java
  trading-service/controllers/OrderController.go
  trading-service/controllers/orders/Matching.go
Labels: approved, lgtm, size/L

#313 Ruta za ukupan profit banke
  trading-service/controllers/OrderController.go
  trading-service/dto/ProfitDTO.go
  trading-service/services/ProfitService.go
Labels: approved, size/M, lgtm

#315 Add deploy to k8s
  .prow/deploy.yaml
Labels: approved, size/M

#318 Tax
  banking-service/src/main/java/com/banka1/banking/dto/TaxCollectionDTO.java
  banking-service/src/main/java/com/banka1/banking/listener/TaxListener.java
  banking-service/src/main/java/com/banka1/banking/services/TaxService.java
  banking-service/src/main/resources/application.properties
  banking-service/src/test/java/com/banka1/banking/services/TaxServiceTest.java
  go.sum
  trading-service/broker/wrappers.go
  trading-service/controllers/TaxController.go
  trading-service/controllers/tax_test.go
  trading-service/dto/TaxCollectionDTO.go
  trading-service/go.mod
Labels: approved, lgtm, size/L

#317 U data.sql u banking-service su izmenjeni time-stampovi za datume kreiranja i isteka kartica kako bi radilo i prikazivalo normalne datumeCard expiration date
  banking-service/src/main/resources/data.sql
Labels: approved, size/M, lgtm

#314 Otc interbank
  banking-service/src/main/java/com/banka1/banking/services/OTCService.java
  trading-service/.env
  trading-service/broker/listeners.go
  trading-service/controllers/OTCTradeController.go
  trading-service/controllers/TaxController.go
  trading-service/controllers/orders/Load.go
  trading-service/dto/Interbank.go
  trading-service/middlewares/Auth.go
  trading-service/types/Models.go
Labels: approved, lgtm, size/XXL

#319 forward interbank poruka na trading servis
  banking-service/src/main/java/com/banka1/banking/config/InterbankConfig.java
  banking-service/src/main/java/com/banka1/banking/config/InterbankInterceptor.java
  banking-service/src/main/java/com/banka1/banking/services/EventExecutorService.java
  banking-service/src/main/java/com/banka1/banking/services/InterbankService.java
  banking-service/src/main/java/com/banka1/banking/services/requests/RequestBuilder.java
  banking-service/src/main/java/com/banka1/banking/services/requests/RequestService.java
  banking-service/src/main/resources/application.properties
  compose.local.yaml
Labels: approved, lgtm, size/L

#309 new payment logika marija rekla dobro
  banking-service/src/main/java/com/banka1/banking/services/ExchangeService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/test/java/com/banka1/banking/services/EventExecutorServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/EventServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/InterbankServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/OrderServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/OtcServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransferServiceTest.java
Labels: approved, lgtm, size/XL

#320 Testovi
  banking-service/build.gradle
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/test/java/com/banka1/banking/services/CreateForeignBankTransferTest.java
  banking-service/src/test/java/com/banka1/banking/services/EventExecutorServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransferServiceProcessTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransferServiceValidationTest.java
Labels: approved, lgtm

#322 Sredjeno.
  banking-service/src/main/java/com/banka1/banking/controllers/TaxController.java
  trading-service/controllers/OrderController.go
  trading-service/controllers/orders/Matching.go
Labels: approved, lgtm, size/XS

#323 Various small bugfixes
  Caddyfile
  banking-service/src/main/java/com/banka1/banking/dto/AuthorizedPersonDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/CreateAccountByEmployeeDTO.java
  banking-service/src/main/java/com/banka1/banking/mapper/CardMapper.java
  banking-service/src/main/java/com/banka1/banking/models/AuthorizedPerson.java
  banking-service/src/main/java/com/banka1/banking/services/OTCService.java
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/dto/DtoTest.java
  compose.yaml
  notification-service/src/main/java/com/banka1/notification/Test.java
  notification-service/src/main/resources/application.properties
  user-service/src/main/java/com/banka1/user/DTO/banking/CreateAccountDTO.java
  user-service/src/main/java/com/banka1/user/config/GlobalExceptionHandler.java
  user-service/src/main/java/com/banka1/user/service/EmployeeService.java
  user-service/src/main/resources/application-postgres.properties
  user-service/src/main/resources/application.properties
  user-service/src/main/resources/data.sql
Labels: approved, size/M, lgtm

#326 fix get tax
  banking-service/src/main/java/com/banka1/banking/services/TaxService.java
  banking-service/src/test/java/com/banka1/banking/services/TaxServiceTest.java
  trading-service/controllers/TaxController.go
Labels: approved, lgtm, size/L

#327 Let's say that buying / selling forex works
  banking-service/src/main/java/com/banka1/banking/repository/AccountRepository.java
  banking-service/src/main/java/com/banka1/banking/services/BankAccountUtils.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/main/resources/data.sql
  trading-service/controllers/orders/Load.go
Labels: approved, size/M, lgtm

#328 Update build.yml
  .prow/build.yml
Labels: approved, lgtm, size/XS

#329 Fix spec compliance issus in interbank money transfer
  Caddyfile
  banking-service/src/main/java/com/banka1/banking/config/InterbankDeliveryInterceptor.java
  banking-service/src/main/java/com/banka1/banking/config/InterbankInterceptor.java
  banking-service/src/main/java/com/banka1/banking/controllers/ExchangeController.java
  banking-service/src/main/java/com/banka1/banking/controllers/InterbankController.java
  banking-service/src/main/java/com/banka1/banking/controllers/OtpTokenController.java
  banking-service/src/main/java/com/banka1/banking/controllers/TransferController.java
  banking-service/src/main/java/com/banka1/banking/dto/OtpTokenDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/committx/CommitTransactionDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/ForeignBankIdDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/InterbankTransactionDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/PostingDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/TxAccountDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/assets/CurrencyAsset.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/assets/MonetaryAssetDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/rollbacktx/RollbackTransactionDTO.java
  banking-service/src/main/java/com/banka1/banking/models/Event.java
  banking-service/src/main/java/com/banka1/banking/models/EventDelivery.java
  banking-service/src/main/java/com/banka1/banking/models/OtpToken.java
  banking-service/src/main/java/com/banka1/banking/models/Transfer.java
  banking-service/src/main/java/com/banka1/banking/models/helper/IdempotenceKey.java
  banking-service/src/main/java/com/banka1/banking/repository/EventDeliveryRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/EventRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/OtpTokenRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/TransactionRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/TransferRepository.java
  banking-service/src/main/java/com/banka1/banking/services/EventExecutorService.java
  banking-service/src/main/java/com/banka1/banking/services/EventService.java
  banking-service/src/main/java/com/banka1/banking/services/ExchangeService.java
  banking-service/src/main/java/com/banka1/banking/services/InterbankService.java
  banking-service/src/main/java/com/banka1/banking/services/OtpTokenService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/main/resources/application.properties
  banking-service/src/main/resources/data.sql
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/controller/ExchangeControllerTest.java
  banking-service/src/test/java/com/banka1/banking/service/AuthServiceTests.java
  banking-service/src/test/java/com/banka1/banking/service/LoanPaymentSchedulerTest.java
  banking-service/src/test/java/com/banka1/banking/services/CreateForeignBankTransferTest.java
  banking-service/src/test/java/com/banka1/banking/services/EventServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/ExchangeServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/ExternalTransferServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/ExternalTransferServiceUnitTest.java
  banking-service/src/test/java/com/banka1/banking/services/InterbankServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/InternalTransferServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/OtpTokenServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransactionServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransferServiceProcessTest.java
  banking-service/src/test/java/com/banka1/banking/services/TransferServiceTest.java
  compose.yaml
  trading-service/.env
  trading-service/controllers/OTCTradeController.go
  user-service/src/main/java/com/banka1/user/controllers/CustomerController.java
Labels: approved, lgtm, size/XXL

#331 interbank
  banking-service/src/main/java/com/banka1/banking/config/InterbankConfig.java
  banking-service/src/main/resources/application.properties
  compose.local.yaml
Labels: size/S, approved, lgtm

#332 Fix interbank
  banking-service/src/main/java/com/banka1/banking/aspect/AuthAspect.java
  banking-service/src/main/java/com/banka1/banking/config/InterbankDeliveryInterceptor.java
  banking-service/src/main/java/com/banka1/banking/controllers/InterbankController.java
  banking-service/src/main/java/com/banka1/banking/dto/CreateEventDeliveryDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/ForeignBankIdDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/PostingDTO.java
  banking-service/src/main/java/com/banka1/banking/dto/interbank/newtx/assets/OptionDescription.java
  banking-service/src/main/java/com/banka1/banking/models/Account.java
  banking-service/src/main/java/com/banka1/banking/models/helper/IdempotenceKey.java
  banking-service/src/main/java/com/banka1/banking/repository/EventRepository.java
  banking-service/src/main/java/com/banka1/banking/repository/TransferRepository.java
  banking-service/src/main/java/com/banka1/banking/services/EventExecutorService.java
  banking-service/src/main/java/com/banka1/banking/services/EventService.java
  banking-service/src/main/java/com/banka1/banking/services/InterbankService.java
  banking-service/src/main/java/com/banka1/banking/services/TransferService.java
  banking-service/src/main/resources/application.properties
  banking-service/src/main/resources/schema.sql
  banking-service/src/test/java/com/banka1/banking/services/EventExecutorServiceTest.java
  banking-service/src/test/java/com/banka1/banking/services/EventServiceTest.java
  trading-service/.env
  trading-service/controllers/OTCTradeController.go
  trading-service/controllers/SecuritiesController.go
  trading-service/db/Database.go
  trading-service/listings/finhub/Finhub.go
  trading-service/main.go
  trading-service/middlewares/Auth.go
  trading-service/types/Models.go
Labels: approved, lgtm, size/XL
